package com.example.moneybuddy2.ui.screens.analytics

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.example.moneybuddy2.ui.viewmodel.AnalyticsUiState
import com.example.moneybuddy2.data.model.CategorySlice
import com.example.moneybuddy2.ui.viewmodel.ChatViewModel
import com.example.moneybuddy2.data.model.Role
import com.example.moneybuddy2.ui.viewmodel.AnalyticsViewModel
import java.time.YearMonth
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
//import com.github.fracassi_marco.jetchart.piechart.PieChart
//import com.github.fracassi_marco.jetchart.piechart.Pies
//import com.github.fracassi_marco.jetchart.piechart.Slice
//import com.github.fracassi_marco.jetchart.piechart.drawers.FilledSliceDrawer
//import com.github.fracassi_marco.jetchart.animation.fadeInAnimation

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun AnalyticsScreen(vm: AnalyticsViewModel, onBack: () -> Unit) {
    val ui by vm.ui.collectAsState()

    LaunchedEffect(Unit) { vm.load() }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Analytics") },
                navigationIcon = {
                    IconButton(onClick = onBack) { Icon(Icons.Default.ArrowBack, null) }
                }
            )
        }
    ) { padding ->
        if (ui.loading) {
            LinearProgressIndicator(Modifier.fillMaxWidth().padding(padding))
        }

        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(12.dp)
        ) {
            ui.error?.let { Text(it, color = MaterialTheme.colorScheme.error) }
            MonthPickerRow(selected = ui.selectedMonth, onSelect = vm::setMonth)
            SpendingOverviewCard(ui)

            CategoryPieCard(ui.categoryTotals)

            CategoryRankList(ui.categoryTotals)

           // ExpensesThisMonthList(ui.expensesThisMonth)

            SustainabilityCard(
                dailyAverage = ui.dailyAverage,
                monthlyCarbonKg = ui.monthlyCarbonKg,
                treesEquivalent = ui.treesEquivalent
            )
        }
    }
}

@Composable
fun SpendingOverviewCard(ui: AnalyticsUiState) {
    Card {
        Column(Modifier.padding(12.dp), verticalArrangement = Arrangement.spacedBy(6.dp)) {
            Text("Spending overview", style = MaterialTheme.typography.titleMedium)
            Text("Total: RM %.2f".format(ui.thisMonthTotal), style = MaterialTheme.typography.headlineSmall)

            val pct = ui.pctChangeVsLastMonth
            val changeText = if (pct == null) {
                "Change vs last month: —"
            } else {
                val sign = if (pct >= 0) "+" else ""
                "Change vs last month: $sign%.1f%%".format(pct)
            }
            Text(changeText)
            Text("Last month: RM %.2f".format(ui.lastMonthTotal), style = MaterialTheme.typography.bodySmall)
        }
    }
}

@Composable
fun CategoryPieCard(slices: List<CategorySlice>) {
    Card {
        Column(Modifier.padding(12.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
            Text("Category breakdown", style = MaterialTheme.typography.titleMedium)

//            if (slices.isEmpty()) {
//                Text("No expenses this month.")
//                return
//            }

            // Simple pie chart (colors auto-generated by default Material colors is non-trivial;
            // easiest is to pass a list of Colors. If you want, I can generate a stable palette.)
//            PieChartCanvas(
//                values = slices.map { it.amount },
//                labels = slices.map { it.category }
//            )
        }
    }
}

@Composable
fun CategoryRankList(slices: List<CategorySlice>) {
    Card {
        Column(Modifier.padding(12.dp), verticalArrangement = Arrangement.spacedBy(6.dp)) {
            Text("Categories (ranked)", style = MaterialTheme.typography.titleMedium)

            if (slices.isEmpty()) {
                Text("—")
                return@Card
            }

            slices.forEach { s ->
                Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                    Text("${s.category} (${s.percent.toInt()}%)")
                    Text("RM %.2f".format(s.amount))
                }
            }
        }
    }
}

@Composable
fun SustainabilityCard(
    dailyAverage: Double,
    monthlyCarbonKg: Double?,
    treesEquivalent: Double?
) {
    Card (
        modifier = Modifier
            .fillMaxWidth()
            .heightIn(max = 320.dp)
    ){
        Column(modifier = Modifier
            .verticalScroll(rememberScrollState())
            .padding(12.dp),
            verticalArrangement = Arrangement.spacedBy(6.dp)
        ) {
            Text("Sustainability insights", style = MaterialTheme.typography.titleMedium)
            Text("Daily average spending: RM %.2f".format(dailyAverage))

            if (monthlyCarbonKg == null) {
                Text("Carbon estimate: — (no eligible categories yet)")
            } else {
                Text("Estimated carbon (this month): %.2f kgCO₂e".format(monthlyCarbonKg))
                treesEquivalent?.let {
                    Text("Tree equivalent (assumption-based): %.2f trees/year".format(it))
                    Text(
                        "Note: This uses a configurable absorption assumption; it varies by species and environment.",
                        style = MaterialTheme.typography.bodySmall
                    )
                }
            }

            // Very simple rule-based recommendations (extend later)
            if ((monthlyCarbonKg ?: 0.0) > 0.0) {
                Text("Recommendations", style = MaterialTheme.typography.titleSmall)
                Text("• Review Transport spending; consider consolidating trips or using public transport when feasible.")
                Text("• Set a monthly transport budget to monitor trends.")
            }
        }
    }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun MonthPickerRow(
    selected: YearMonth,
    onSelect: (YearMonth) -> Unit
) {
    val months = remember {
        val now = YearMonth.now()
        (0..11).map { now.minusMonths(it.toLong()) }
    }

    var expanded by remember { mutableStateOf(false) }

    ExposedDropdownMenuBox(expanded = expanded, onExpandedChange = { expanded = !expanded }) {
        TextField(
            value = selected.toString(), // format nicer if you want
            onValueChange = {},
            readOnly = true,
            label = { Text("Month") },
            trailingIcon = { ExposedDropdownMenuDefaults.TrailingIcon(expanded) },
            modifier = Modifier.menuAnchor()
        )
        ExposedDropdownMenu(expanded = expanded, onDismissRequest = { expanded = false }) {
            months.forEach { m ->
                DropdownMenuItem(
                    text = { Text(m.toString()) },
                    onClick = { expanded = false; onSelect(m) }
                )
            }
        }
    }
}
//@Composable
//fun CategoryPieChart(
//    slices: List<CategorySlice>,
//    modifier: Modifier = Modifier,
//    donutThickness: Float = 60f
//) {
//    if (slices.isEmpty()) return
//
//    // Simple stable palette (you can improve later)
//    val palette = remember {
//        listOf(
//            Color(0xFF4E79A7),
//            Color(0xFFF28E2B),
//            Color(0xFFE15759),
//            Color(0xFF76B7B2),
//            Color(0xFF59A14F),
//            Color(0xFFEDC948),
//            Color(0xFFB07AA1),
//            Color(0xFFFF9DA7),
//            Color(0xFF9C755F),
//            Color(0xFFBAB0AC)
//        )
//    }
//
//    val jetSlices = remember(slices) {
//        slices.mapIndexed { idx, s ->
//            Slice(
//                value = s.amount.toFloat(),
//                color = palette[idx % palette.size]
//            )
//        }
//    }
//
//    PieChart(
//        pies = Pies(jetSlices),
//        modifier = modifier,
//        animation = fadeInAnimation(900),
//        sliceDrawer = FilledSliceDrawer(thickness = donutThickness) // thickness>0 = donut
//    )
//}
//



